package com.digitalwellbeingguard.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF146a5c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF86d2c1)
val md_theme_light_onPrimaryContainer = Color(0xFF005c4f)
val md_theme_light_secondary = Color(0xFF62568d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcfc1ff)
val md_theme_light_onSecondaryContainer = Color(0xFF584c82)
val md_theme_light_tertiary = Color(0xFF30628a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF99c9f6)
val md_theme_light_onTertiaryContainer = Color(0xFF1f557b)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFfaf9f6)
val md_theme_light_onBackground = Color(0xFF1a1c1a)
val md_theme_light_surface = Color(0xFFfaf9f6)
val md_theme_light_onSurface = Color(0xFF1a1c1a)
val md_theme_light_surfaceVariant = Color(0xFFe3e2e0)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4946)
val md_theme_light_outline = Color(0xFF6f7976)
val md_theme_light_inverseOnSurface = Color(0xFFf2f1ee)
val md_theme_light_inverseSurface = Color(0xFF2f312f)
val md_theme_light_inversePrimary = Color(0xFF89d5c4)

val premium_gradient_primary_start = Color(0xFF86d2c1)
val premium_gradient_primary_end = Color(0xFF76c3b2)

val premium_gradient_secondary_start = Color(0xFFcfc1ff)
val premium_gradient_secondary_end = Color(0xFFc0b0f5)
